version: '3'
services:
  circus-database:
    container_name: circus_database
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: circus
      POSTGRES_PASSWORD: circus
      POSTGRES_DB: circus
    restart: always
    ports:
      - "5432:5432"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_BROKER_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    command: sh -c "((sleep 15 && kafka-topics --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 3 --topic room)&) && /etc/confluent/docker/run"
  circus-service:
    container_name: circus_service
    image: circus-service
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - circus-database
      - circus-kafka
    ports:
      - "8080:8080"
    restart: always
    links:
      - circus-database
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"